### ISSUE TITLE
Leiko_5_Запрос на статус эксперта

### ISSUE THREAD

**Issue by TatianaLeiko** [arthur-space/InvestArena#14]
Портал Инвестарена рад экспертам и приглашает к сотрудничеству специалистов. Вы можете зарабатывать сами и помогать зарабатывать другим. Публикуя прогнозы по своим сделкам вы получите возможность  получать за это дополнительное вознаграждение от портала Инвестарена. 

Для того, чтобы стать экспертом нужно показать хорошую статистику и соответствовать определенным критериям:

1.	Открывать сделки на площадке Инвестарена у своего брокера
2.	Наличие торговой статистики минимум за 3 месяца
3.	Не менее 10 сделок в месяц, каждая из них объемом не менее 0,1.
4.	Количество прибыльных сделок не ниже 75% 
5.	Отношение прибыли к убытку в пипсах за общее количество сделок не менее 3:1

Чтобы узнать больше или если Вы понимаете, что соответствуете данным критериям, свяжитесь с нами. 

**_Дальше нужна кнопка Оставить заявку или Запрос._**

**Comment by vadimlevchenko** [comment]
https://maxiproject.atlassian.net/browse/ST-2500

**Comment by FoxyTeacher** [comment]
Mobile - https://maxiproject.atlassian.net/browse/ST-2501?atlOrigin=eyJpIjoiY2YyODA1OWVhZWE0NGE4MWEwOTgwYjJhMGRlMjNkMTMiLCJwIjoiaiJ9
