### ISSUE TITLE
Поменять цветовое решение на мобильной версии, как на desktop 

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#15]
- Стартовая страница с каруселькой (голубой)
- регистрация/вход белый
- общий фон голубой 
- панель навигации 
- цвет шрифта (баланс и P&L) в главном хедере
- Все иконки (профиль юзера, инструменты, торговля)

**Comment by vadimlevchenko** [comment]
https://maxiproject.atlassian.net/browse/ST-2533
