### ISSUE TITLE
[Mobile] Объединить брокера и депозит  

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#16]
При подключении брокера иконка не меняется на иконку кошелек (депозит) 
При подключенном брокере добавить поле выбора аккаунта после поля с платформой  
При подключенном брокере добавить кнопку "депозит" перед кнопкой "отключить" (переход на отдельную страницу)
Растянуть текст Мы не храним Ваши пароли... на две строки
![image](https://user-images.githubusercontent.com/61138813/91702378-4fc76e80-eb81-11ea-8d69-8bc270c23b59.png)

**Comment by vadimlevchenko** [comment]
https://maxiproject.atlassian.net/browse/ST-2523
