### ISSUE TITLE
[#2] Добавление фейковых людей в вип группу

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#2]

**Comment by arthur-space** [comment]
При создании Вип группы менеджер должен иметь возможность добавить количество пользователей от 0 до 300.
Добавить дополнительное поле (не обязательное поле для заполнения) для ввода цифр в модалку для создания группы,
назвать поле "Добавить в группу пользователей (ботов)"
В случае пустого поля на бек отправляется дефолт 0
Валидация должна не пропускать число 301 и более, отрицательные,буквы и спец символы

**Comment by RomanPrisyazhnuk** [comment]
BE 2 QA2
FE 2 FEM 1 QA 1
