### ISSUE TITLE
[Adm] Добавить в админку для промо две торговые платформы LimeFX и TradeAllCrypto

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#20]

**Comment by vadimlevchenko** [comment]
https://maxiproject.atlassian.net/browse/ST-2519
https://maxiproject.atlassian.net/browse/ST-2520

**Comment by FoxyTeacher** [comment]
https://maxiproject.atlassian.net/browse/ST-2555?atlOrigin=eyJpIjoiZGU1YTYyYjUwYmM1NDlmOTk5MjdjNWZjYzg3OTlhYWMiLCJwIjoiaiJ9
