### ISSUE TITLE
[Desktop, Mobile] Telegram

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#22]
Добавить в навигацию последним пунктом, после "Обратная связь" и перед баннером, Telegram канал (при клике должен осуществляться переход на телеграмм канал https://t.me/investarena_analytics ) иконка телеграмма

**Comment by FoxyTeacher** [comment]
Desktop - https://maxiproject.atlassian.net/browse/ST-2542?atlOrigin=eyJpIjoiNzNmMzI1OWFlZGI0NGEwMjg1MWZhMjAwNzg1OWI5MDciLCJwIjoiaiJ9

Mobile - https://maxiproject.atlassian.net/browse/ST-2543?atlOrigin=eyJpIjoiYmY3ZjU3YmIyNjU5NGUyYTk2ODFmMDBjMzJmZDU1NTgiLCJwIjoiaiJ9
