### ISSUE TITLE
[#6] Механизм работы лайков 

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#6]
Для того что бы разгрузить сервер Запись лайков в базу без авторизации этого бота.
Механика такова: 
При создании поста на беке запускается процесс при котором с переодичностью раз в 10 секунд идет запись в базу о лайках ботов из нашего списка. за период 20 мин записываются лайки в базу.
При этом лайки не отправляются по WS на фронт.

**Comment by RomanPrisyazhnuk** [comment]
BE 2 QA2
