### ISSUE TITLE
[#9] Название инструмента Mobile, desktop 

### ISSUE THREAD

**Issue by arthur-space** [arthur-space/InvestArena#9]
**Desktop** 
На странице инструмента к примеру AUD/CAD в левом сайдбаре добавить блок с названием  и логотипом инструмента.
Блок такой же как внутри Вип групп (без закладок)
 Добавить "избранное" вместо закладок

![image](https://user-images.githubusercontent.com/61138813/91714299-16e4c500-eb94-11ea-93cb-0f1315ad10f9.png)

![image](https://user-images.githubusercontent.com/61138813/91714362-38de4780-eb94-11ea-84bb-1635447ab203.png)

**Mobile**
На странице инструмента к названию добавить иконку инструмента.
Под названием инструментом добавить разделитель 

![image](https://user-images.githubusercontent.com/61138813/90631071-c9c73180-e22a-11ea-9998-68c3008a71bc.png)

**Comment by arthur-space** [comment]
![image](https://user-images.githubusercontent.com/61138813/90630494-cb442a00-e229-11ea-938d-77d0fd8bb134.png)

**Comment by FoxyTeacher** [comment]
Mobile - https://maxiproject.atlassian.net/browse/ST-2527?atlOrigin=eyJpIjoiOTcxYWRjZTgzNWUxNGZjOGE3N2ZmNjI2ZjcyNjQxOWUiLCJwIjoiaiJ9

Desktop - https://maxiproject.atlassian.net/browse/ST-2528?atlOrigin=eyJpIjoiMDk5N2Q0ZThhMjkwNDZkZDgyMzYxNWZhOGMzYjI4NjYiLCJwIjoiaiJ9
